name: Wormhole
version: '1.0.0'
main: me.antritus.minecraft_server.wormhole.Wormhole
description: Teleport plugin made for requesting and accepting teleports.
api-version: '1.20'
authors:
  - Antritus
  - Lunarate